development:
  clients:
    default:
      database: pathfinder_development
      hosts:
        - localhost:27017
      options:
        max_pool_size: 25
        min_pool_size: 10
  options:
test:
  clients:
    default:
      database: pathfinder_test
      hosts:
        - localhost:27017